### ISSUE TITLE
Changer couleur des autres participants

### ISSUE THREAD

**Issue by bastien-boulard** [danfr/DNC42#1]
La couleur des pseudos des autres participants étant choisie aléatoirement (local), il arrive parfois que plusieurs participants partagent la même couleur ce qui rend la discussion plus difficilement lisible.

Pour un meilleur confort visuel il serait préférable de pouvoir modifier (local) la couleur des autres participants via un clic droit sur le pseudo par exemple.

**Comment by danfr** [comment]
Le changement manuel de la couleur n'a pas été implémenté, cependant le système d'affectation des couleurs a été revu pour éviter les doublons.
